# dai-lab-http-infrastructure
# Step 3: HTTP API server
# Authors: Gabriel Barros Fernandez - Dylan Stegmuller
# Date: 16.12.2024

# Defining services
services:
  reverse_proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
  # Web Service
  web:
    image: nginx
    # Build context and Dockerfile to use
    build:
      context: ./nginx/
      dockerfile: Dockerfile    # Volumes
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.http.routers.web.rule=Host(`192.168.56.12`)"
  api:
    image: api
    # Build context and Dockerfile to use
    build:
      context: ./api/
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.api.rule=Host(`192.168.56.12`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.middlewares=strip-api-prefix"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
