# dai-lab-http-infrastructure
# Step 2: Docker compose
# Authors: Gabriel Barros Fernandez - Dylan Stegmuller
# Date: 13.12.2024

# Defining services
services:
  # Web Service
  web:
    image: nginx
    # Port mapping
    ports:
      - "8080:80"
    # Volumes
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
